name: continuous integration
on:
  push:
    branches:
      - '**'

jobs:

  run_tests_for_bidrag_sjablon_without_security:
    runs-on: self-hosted

    steps:
      - uses: navikt/bidrag-integration/cucumber-clone@v5
        id: clone
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: navikt/bidrag-integration/input-json@v5
        with:
          base_path: ${{ steps.clone.outputs.cucumber_path }}
      - uses: navikt/bidrag-scripts/create-cucumber-shell@feature/args
        id: creator
        with:
          cucumber_tag: bidrag-sjablon
      - run: ${{ steps.creator.outputs.created_shell }}

  run-tests:
    runs-on: self-hosted
    name: run cucumber integration tests
    needs: run_tests_for_bidrag_sjablon_without_security

    steps:
      - run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            ENVIRONMENT=main
          elif [[ $GITHUB_REF == "refs/heads/feature/main.environment" ]]; then
            ENVIRONMENT=main
          else
            ENVIRONMENT=feature
          fi

          echo BRANCH=$ENVIRONMENT >> $GITHUB_ENV
      - run: kubectl config use-context dev-fss
      - name: restart bidrag-testdata
        if: env.BRANCH == 'main'
        run: |
          PODS_TESTDATA=$(kubectl get pods -n bidrag -l app=bidrag-testdata | awk '{print $1}' | grep -v NAME)
          kubectl delete pods -n bidrag $(echo $PODS_TESTDATA | sed 's;\n; ;')
      - name: restart bidrag-testdata-feature
        if: env.BRANCH == 'feature'
        run: |
          PODS_TESTDATA=$(kubectl get pods -n bidrag -l app=bidrag-testdata-feature  | awk '{print $1}' | grep -v NAME)
          kubectl delete pods -n bidrag $(echo $PODS_TESTDATA | sed 's;\n; ;')
      - uses: navikt/bidrag-integration/cucumber-clone-tags@v5
        id: tags
        env:
          WORKFLOW_CREDENTIALS: "jactor-rises:${{ secrets.WORKFLOW_TOKEN }}"
      - uses: navikt/bidrag-integration/input-json@v5
        id: integration
        with:
          applications: ${{ steps.tags.outputs.cloned_apps }}
          base_path: ${{ steps.tags.outputs.cucumber_path }}
          test_username: z992903
      - uses: navikt/bidrag-scripts/create-cucumber-shell@v1
        id: creator
        with:
          user: j104364
      - run: ${{ steps.creator.outputs.created_shell }}
        env:
          PIP_USER_AUTHENTICATION: ${{ secrets.PIP_USER_AUTHENTICATION }}
          TEST_USER_AUTHENTICATION: ${{ secrets.TEST_USER_AUTHENTICATION }}
          USER_AUTHENTICATION: ${{ secrets.USER_AUTHENTICATION }}
      - name: Remove files from workspace
        run: |
          cd $RUNNER_WORKSPACE
          sudo rm -rf *
        if: ${{ always() }}

  bump_dev_version:
    runs-on: ubuntu-latest
    name: Bump SNAPSHOT version
    if: github.ref == 'refs/heads/main'
    needs: run-tests

    steps:
      - uses: actions/checkout@v2
      - run: |
          BUMP_DEV_VERSION=true
          LAST_COMMIT=$(git log -1 --oneline)
          BUMP_MESSAGE="Bumped to new version"

          if [[ "$LAST_COMMIT" == *"$BUMP_MESSAGE"* ]]; then
            $BUMP_DEV_VERSION=false
          fi

          echo BUMP_DEV_VERSION=$BUMP_DEV_VERSION >> $GITHUB_ENV
      - uses: actions/cache@v1
        if: env.BUMP_DEV_VERSION == 'true'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn release:update-versions
        if: env.BUMP_DEV_VERSION == 'true'
      - run: |
          BUMPED_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo ::set-output name=version::${BUMPED_VERSION}
        id: snapshot
      - uses: navikt/bidrag-git/commit@v3
        if: env.BUMP_DEV_VERSION == 'true'
        with:
          commit_message: "Bumped to new version: ${{ steps.snapshot.outputs.version }}"
          pattern: "pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
