name: continuous integration
on:
  push:
    branches:
      - '**'

jobs:

  run-tests:
    runs-on: self-hosted
    name: run cucumber integration tests

    steps:
      - run: kubectl config use-context dev-fss
      - name: restart bidrag-dokument-testdata pods for pods in the default namespace
        if: github.ref == 'refs/heads/main'
        run: |
          PODS_TESTDATA=$(kubectl get pods -l app=bidrag-dokument-testdata | awk '{print $1}' | grep -v NAME)
          kubectl delete pods $(echo $PODS_TESTDATA | sed 's;\n; ;')
      - name: restart bidrag-dokument-testdata pods for pods in the feature namespace
        if: github.ref != 'refs/heads/main'
        run: |
          PODS_TESTDATA=$(kubectl get pods -n q1 -l app=bidrag-dokument-testdata  | awk '{print $1}' | grep -v NAME)
          kubectl delete pods -n q1 $(echo $PODS_TESTDATA | sed 's;\n; ;')
      - uses: navikt/bidrag-integration/cucumber-clone-tags@v4
        env:
          WORKFLOW_CREDENTIALS: "jactor-rises:${{ secrets.WORKFLOW_TOKEN }}"
      - name: wait for bidrag-dokument-testdata to deploy after restart
        run: |
            echo wait for bidrag-dokument-testdata to deploy after restart
            while [ $(kubectl get pods -l app=bidrag-dokument-testdata | awk '{print $2}' | grep -v READY | grep 0/1 | wc -l) -ne 0 ]
            do
              echo -n "..."
            done
      - uses: navikt/bidrag-maven/cucumber-backend@v5
        with:
          maven_command: test
          maven_image: maven:3.6.3-openjdk-15
          username: j104364
          test_user: z992903
          pip_user: srvbisys
        env:
          USER_AUTHENTICATION: ${{ secrets.USER_AUTHENTICATION }}
          TEST_USER_AUTHENTICATION: ${{ secrets.TEST_USER_AUTHENTICATION }}
          PIP_USER_AUTHENTICATION: ${{ secrets.PIP_USER_AUTHENTICATION }}
      - name: Remove files from workspace
        run: |
          cd $RUNNER_WORKSPACE
          echo deleting files
          ls -al
          sudo rm -rf *
        if: ${{ failure() || success() }}

  bump_dev_version:
    runs-on: ubuntu-latest
    name: Bump SNAPSHOT version
    if: github.ref == 'refs/heads/main'
    needs: run-tests

    steps:
      - uses: actions/checkout@v2
      - run: |
          MSG=$(git log --format=%B -n 1 $(git rev-parse HEAD) | cat -)

          [[ "$MSG" == "Bumped"* ]] && echo do_commit=false >> $GITHUB_ENV || echo do_commit=true >> $GITHUB_ENV
      - run: env
      - uses: actions/cache@v1
        if: env.do_commit == 'true'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - uses: navikt/bidrag-maven/setup@v4
        if: env.do_commit == 'true'
      - run: mvn release:update-versions
        if: env.do_commit == 'true'
      - run: |
          BUMPED_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo ::set-output name=version::${BUMPED_VERSION}
        id: snapshot
        if: env.do_commit == 'true'
      - uses: navikt/bidrag-git/commit@v3
        if: env.do_commit == 'true'
        with:
          commit_message: "Bumped to new version: ${{ steps.snapshot.outputs.version }}"
          pattern: "pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
