name: continuous integration
on:
  push:
    branches:
      - '**'

jobs:

  run-tests:
    runs-on: self-hosted
    name: run cucumber integration tests

    steps:
      - run: kubectl config use-context dev-fss
      - name: restart bidrag-testdata
        if: github.ref == 'refs/heads/main'
        run: |
          PODS_TESTDATA=$(kubectl get pods -n bidrag -l app=bidrag-testdata | awk '{print $1}' | grep -v NAME)
          kubectl delete pods -n bidrag $(echo $PODS_TESTDATA | sed 's;\n; ;')
      - name: restart bidrag-testdata-feature
        if: github.ref != 'refs/heads/main'
        run: |
          PODS_TESTDATA=$(kubectl get pods -n bidrag -l app=bidrag-testdata-feature  | awk '{print $1}' | grep -v NAME)
          kubectl delete pods -n bidrag $(echo $PODS_TESTDATA | sed 's;\n; ;')
      - run: git clone --depth 1 https://github.com/navikt/bidrag-scripts
      - run: git clone https://github.com/navikt/bidrag-dokument-cucumber
      - uses: fwilhe2/setup-kotlin@0.2.0
      - run: kotlinc -script $GITHUB_WORKSPACE/bidrag-scripts/src/kotlin/produceCucumberShell.kts \
               false test maven:3.6.3-openjdk-15 j104364 json/integrationInput.json bidrag-cucumber-backend/execute-cucumber.sh
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
      - run: ls -al $GITHUB_WORKSPACE/bidrag-cucumber-backend
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
      - run: |
          CUCE_FILE=$GITHUB_WORKSPACE/bidrag-cucumber-backend/execute-cucumber.sh

          if test -f "$CUCE_FILE"; then
            sudo chmod +x "$CUCE_FILE"
          else
            exit 1
          fi
        env:
          GITHUB_WORKSPACE: ${{ github.workspace }}
      - uses: navikt/bidrag-integration/cucumber-clone-tags@v5
        id: tags
        env:
          WORKFLOW_CREDENTIALS: "jactor-rises:${{ secrets.WORKFLOW_TOKEN }}"
      - uses: navikt/bidrag-integration/input-json@v5
        id: integration
        with:
          applications: ${{ steps.tags.outputs.cloned_apps }}
          base_path: ${{ steps.tags.outputs.cucumber_path }}
          test_username: z992903
      - run: ./execute-cucumber.sh
        env:
          USER_AUTHENTICATION: ${{ secrets.USER_AUTHENTICATION }}
          TEST_USER_AUTHENTICATION: ${{ secrets.TEST_USER_AUTHENTICATION }}
          PIP_USER_AUTHENTICATION: ${{ secrets.PIP_USER_AUTHENTICATION }}
      - name: Remove files from workspace
        run: |
          cd $RUNNER_WORKSPACE
          echo deleting files
          ls -al
          sudo rm -rf *
        if: ${{ failure() || success() }}

  bump_dev_version:
    runs-on: ubuntu-latest
    name: Bump SNAPSHOT version
    if: github.ref == 'refs/heads/main'
    needs: run-tests

    steps:
      - uses: actions/checkout@v2
      - run: |
          BUMP_DEV_VERSION=true
          LAST_COMMIT=$(git log -1 --oneline)
          BUMP_MESSAGE="Bumped to new version"

          if [[ "$LAST_COMMIT" == *"$BUMP_MESSAGE"* ]]; then
            $BUMP_DEV_VERSION=false
          fi

          echo BUMP_DEV_VERSION=$BUMP_DEV_VERSION >> $GITHUB_ENV
      - uses: actions/cache@v1
        if: env.BUMP_DEV_VERSION == 'true'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn release:update-versions
        if: env.BUMP_DEV_VERSION == 'true'
      - run: |
          BUMPED_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo ::set-output name=version::${BUMPED_VERSION}
        id: snapshot
      - uses: navikt/bidrag-git/commit@v3
        if: env.BUMP_DEV_VERSION == 'true'
        with:
          commit_message: "Bumped to new version: ${{ steps.snapshot.outputs.version }}"
          pattern: "pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
