name: continuous integration
on:
  push:
    branches:
      - '**'

jobs:

  set-up:
    runs-on: self-hosted

    steps:
      - run: |
          if [[ $GITHUB_REF == "refs/heads/main" ]]; then
            ENVIRONMENT=main
          elif [[ $GITHUB_REF == "refs/heads/feature/main.environment" ]]; then
            ENVIRONMENT=main
          else
            ENVIRONMENT=feature
          fi

          echo BRANCH=$ENVIRONMENT >> $GITHUB_ENV
      - name: restart bidrag-testdata
        if: env.BRANCH == 'main'
        run: "curl -X 'POST' 'https://bidrag-testdata.dev.adeo.no/bidrag-testdata/restart' -H 'accept: */*' -d ''"
      - name: restart bidrag-testdata-feature
        if: env.BRANCH == 'feature'
        run: "curl -X 'POST' 'https://bidrag-testdata-feature.dev.adeo.no/bidrag-testdata/restart' -H 'accept: */*' -d ''"
      - uses: navikt/bidrag-integration/cucumber-clone-tags@v5
        id: tags
        env:
          WORKFLOW_CREDENTIALS: "jactor-rises:${{ secrets.WORKFLOW_TOKEN }}"
      - run: echo ${{ steps.tags.outputs.cucumber_path }} > .tag-base-path

  no-auth-bidrag-sjablon:
    runs-on: self-hosted
    name: bidrag-sjablon without security settings
    needs: set-up

    steps:
      - run: echo TAG_BASE_PATH=$( cat .tag-base-path ) >> $GITHUB_ENV
      - uses: navikt/bidrag-integration/input-json@v5
        with:
          applications: ${{ steps.tags.outputs.cloned_apps }}
          base_path: ${{ env.TAG_BASE_PATH }}
      - uses: navikt/bidrag-scripts/create-cucumber-shell@v1
        id: creator
        with:
          cucumber_tag: bidrag-sjablon
      - run: ${{ steps.creator.outputs.created_shell }}
      - run: rm ${{ steps.creator.outputs.created_shell }}
      - run: rm -rf json || echo kunne ikke slette json mappa

  no-auth-bidrag-testdata:
    runs-on: self-hosted
    name: bidrag-testdata without security settings
    needs: no-auth-bidrag-sjablon

    steps:
      - run: echo TAG_BASE_PATH=$( cat .tag-base-path ) >> $GITHUB_ENV
      - uses: navikt/bidrag-integration/input-json@v5
        with:
          applications: ${{ steps.tags.outputs.cloned_apps }}
          base_path: ${{ env.TAG_BASE_PATH }}
      - uses: navikt/bidrag-scripts/create-cucumber-shell@v1
        id: creator
        with:
          cucumber_tag: bidrag-testdata
      - run: ${{ steps.creator.outputs.created_shell }}
      - run: rm ${{ steps.creator.outputs.created_shell }}
      - run: rm -rf json || echo kunne ikke slette json mappa

  run-all-tests:
    runs-on: self-hosted
    name: run cucumber integration tests
    needs: no-auth-bidrag-testdata

    steps:
      - run: echo TAG_BASE_PATH=$( cat .tag-base-path ) >> $GITHUB_ENV
      - uses: navikt/bidrag-integration/input-json@v5
        with:
          applications: ${{ steps.tags.outputs.cloned_apps }}
          base_path: ${{ env.TAG_BASE_PATH }}
          test_username: z992903
      - uses: navikt/bidrag-scripts/create-cucumber-shell@v1
        id: creator
        with:
          user: j104364
      - run: ${{ steps.creator.outputs.created_shell }}
        env:
          PIP_USER_AUTHENTICATION: ${{ secrets.PIP_USER_AUTHENTICATION }}
          TEST_USER_AUTHENTICATION: ${{ secrets.TEST_USER_AUTHENTICATION }}
          USER_AUTHENTICATION: ${{ secrets.USER_AUTHENTICATION }}

  remove-files:
    runs-on: self-hosted
    name: Remove files from workspace
    needs: run-all-tests
    if: ${{ always() }}

    steps:
      - name: Remove files from workspace
        run: |
          cd $RUNNER_WORKSPACE
          sudo rm -rf *

  bump_dev_version:
    runs-on: ubuntu-latest
    name: Bump SNAPSHOT version
    if: github.ref == 'refs/heads/main'
    needs: run-all-tests

    steps:
      - uses: actions/checkout@v2
      - run: |
          BUMP_DEV_VERSION=true
          LAST_COMMIT=$(git log -1 --oneline)
          BUMP_MESSAGE="Bumped to new version"

          if [[ "$LAST_COMMIT" == *"$BUMP_MESSAGE"* ]]; then
            $BUMP_DEV_VERSION=false
          fi

          echo BUMP_DEV_VERSION=$BUMP_DEV_VERSION >> $GITHUB_ENV
      - uses: actions/cache@v1
        if: env.BUMP_DEV_VERSION == 'true'
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - run: mvn release:update-versions
        if: env.BUMP_DEV_VERSION == 'true'
      - run: |
          BUMPED_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo ::set-output name=version::${BUMPED_VERSION}
        id: snapshot
      - uses: navikt/bidrag-git/commit@v3
        if: env.BUMP_DEV_VERSION == 'true'
        with:
          commit_message: "Bumped to new version: ${{ steps.snapshot.outputs.version }}"
          pattern: "pom.xml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
